version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234567
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081